block_size: 9
gen_block_size: 5
confidence_threshold: 0.0
temperature: 1.0
top_k: 50
top_p: 0.95
use_spec_verify: true
draft_conf_file: /root/I-DLM/results/draft_conf_N5.jsonl
# confidence_accept_threshold: 0.5